;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        counsel-yank-pop
        crux-kill-whole-line
        crux-move-beginning-of-line
        crux-smart-open-line-above
        forward-sentence
        forward-sexp
        hydra-multiple-cursors/body
        hydra-window/body
        ignore
        ivy-occur-revert-buffer
        kill-region
        mark-sexp
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        web-mode-element-rename
        web-mode-element-vanish
        web-mode-element-wrap
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        lsp-ui-doc--handle-mouse-movement
        markdown-outdent-or-delete
        mouse-set-region
        sp-remove-active-pair-overlay
        ))
