;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-kill-whole-line
        crux-move-beginning-of-line
        forward-sentence
        ivy-occur-revert-buffer
        kill-region
        mark-sexp
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        web-mode-element-rename
        web-mode-element-vanish
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        ))
