;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	beginning-of-buffer
	comment-dwim
	crux-duplicate-current-line-or-region
	crux-kill-whole-line
	crux-move-beginning-of-line
	crux-smart-open-line-above
	electric-pair-delete-pair
	end-of-buffer
	forward-sexp
	helm-M-x
	helm-for-files
	helm-show-kill-ring
	hydra-window/body
	hydra-window/windmove-left
	hydra-window/windmove-right
	indent-for-tab-command
	js2r-ternary-to-if
	kill-region
	kill-sexp
	mark-sexp
	rjsx-delete-creates-full-tag
	rjsx-electric-gt
	set-linum
	smart-open-line
	xterm-paste
	yaml-electric-backspace
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	multiple-cursors-hydra/*
	multiple-cursors-hydra/body
	multiple-cursors-hydra/mc/edit-lines-and-exit
	multiple-cursors-hydra/mc/mark-all-like-this-and-exit
	multiple-cursors-hydra/mc/mark-next-like-this
	multiple-cursors-hydra/mc/mark-previous-like-this
	multiple-cursors-hydra/mc/skip-to-next-like-this
	multiple-cursors-hydra/mc/skip-to-previous-like-this
	multiple-cursors-hydra/mc/unmark-next-like-this
	))
