;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	crux-kill-whole-line
	crux-move-beginning-of-line
	crux-smart-open-line-above
	helm-M-x
	helm-for-files
	helm-show-kill-ring
	rjsx-delete-creates-full-tag
	set-linum
	smart-open-line
	))

(setq mc/cmds-to-run-once
      '(
	xterm-paste
	))
